system_parameters:
  dt : 0.01
  prediction_horizen : 30
  sampling_number : 10000


distribution_parameters :
  mean : 0
  variance : 0.2

car_parameters :
  length : 2

car_initial_state : 
  initial_x : 0
  initial_y : 0
  initial_theta : 0
  initial_v : 0


target_state :
  x_goal : 20.0
  y_goal : 20.0
  theta_goal : 0.0
  arrival_range : 0.2

weights:
  goal : 1000.0
  tracking : 10.0
  control : 0.1

inverse_temeprature : 1

simulation_parameters :
  frequency : 50