system_parameters:
  dt : 0.01
  prediction_horizen : 30
  sampling_number : 10000

distribution_parameters :
  mean : 0
  variance : 0.2

car_parameters :
  length : 2

car_initial_state : 
  initial_x : 0
  initial_y : 0
  initial_theta : 0
  initial_v : 0

weights:
  goal : 1000.0
  tracking : 10.0
  control : 0.1

inverse_temeprature : 1

simulation_parameters :
  frequency : 50



circle_trajectory :
  x_center : 0.0
  y_center : 10.0
  radius : 5.0
  trajectory_length : 1000
  lane_width : 0.2